/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninImport } from './routes/signin'
import { Route as IndexImport } from './routes/index'
import { Route as ChallengesIndexImport } from './routes/challenges/index'
import { Route as ChallengesSequenceMemoryImport } from './routes/challenges/sequence-memory'
import { Route as ChallengesReactionTimeImport } from './routes/challenges/reaction-time'
import { Route as ChallengesAimTrainerImport } from './routes/challenges/aim-trainer'

// Create/Update Routes

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChallengesIndexRoute = ChallengesIndexImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRoute,
} as any)

const ChallengesSequenceMemoryRoute = ChallengesSequenceMemoryImport.update({
  id: '/challenges/sequence-memory',
  path: '/challenges/sequence-memory',
  getParentRoute: () => rootRoute,
} as any)

const ChallengesReactionTimeRoute = ChallengesReactionTimeImport.update({
  id: '/challenges/reaction-time',
  path: '/challenges/reaction-time',
  getParentRoute: () => rootRoute,
} as any)

const ChallengesAimTrainerRoute = ChallengesAimTrainerImport.update({
  id: '/challenges/aim-trainer',
  path: '/challenges/aim-trainer',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/challenges/aim-trainer': {
      id: '/challenges/aim-trainer'
      path: '/challenges/aim-trainer'
      fullPath: '/challenges/aim-trainer'
      preLoaderRoute: typeof ChallengesAimTrainerImport
      parentRoute: typeof rootRoute
    }
    '/challenges/reaction-time': {
      id: '/challenges/reaction-time'
      path: '/challenges/reaction-time'
      fullPath: '/challenges/reaction-time'
      preLoaderRoute: typeof ChallengesReactionTimeImport
      parentRoute: typeof rootRoute
    }
    '/challenges/sequence-memory': {
      id: '/challenges/sequence-memory'
      path: '/challenges/sequence-memory'
      fullPath: '/challenges/sequence-memory'
      preLoaderRoute: typeof ChallengesSequenceMemoryImport
      parentRoute: typeof rootRoute
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/challenges/aim-trainer': typeof ChallengesAimTrainerRoute
  '/challenges/reaction-time': typeof ChallengesReactionTimeRoute
  '/challenges/sequence-memory': typeof ChallengesSequenceMemoryRoute
  '/challenges': typeof ChallengesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/challenges/aim-trainer': typeof ChallengesAimTrainerRoute
  '/challenges/reaction-time': typeof ChallengesReactionTimeRoute
  '/challenges/sequence-memory': typeof ChallengesSequenceMemoryRoute
  '/challenges': typeof ChallengesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/challenges/aim-trainer': typeof ChallengesAimTrainerRoute
  '/challenges/reaction-time': typeof ChallengesReactionTimeRoute
  '/challenges/sequence-memory': typeof ChallengesSequenceMemoryRoute
  '/challenges/': typeof ChallengesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/challenges/aim-trainer'
    | '/challenges/reaction-time'
    | '/challenges/sequence-memory'
    | '/challenges'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/challenges/aim-trainer'
    | '/challenges/reaction-time'
    | '/challenges/sequence-memory'
    | '/challenges'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/challenges/aim-trainer'
    | '/challenges/reaction-time'
    | '/challenges/sequence-memory'
    | '/challenges/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  ChallengesAimTrainerRoute: typeof ChallengesAimTrainerRoute
  ChallengesReactionTimeRoute: typeof ChallengesReactionTimeRoute
  ChallengesSequenceMemoryRoute: typeof ChallengesSequenceMemoryRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  ChallengesAimTrainerRoute: ChallengesAimTrainerRoute,
  ChallengesReactionTimeRoute: ChallengesReactionTimeRoute,
  ChallengesSequenceMemoryRoute: ChallengesSequenceMemoryRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signin",
        "/challenges/aim-trainer",
        "/challenges/reaction-time",
        "/challenges/sequence-memory",
        "/challenges/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/challenges/aim-trainer": {
      "filePath": "challenges/aim-trainer.tsx"
    },
    "/challenges/reaction-time": {
      "filePath": "challenges/reaction-time.tsx"
    },
    "/challenges/sequence-memory": {
      "filePath": "challenges/sequence-memory.tsx"
    },
    "/challenges/": {
      "filePath": "challenges/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
